CREATE TABLE EMPRESA (
	ID_EMPRESA INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	NOME VARCHAR(200),
	FOTO VARCHAR(1000),
	ICONE VARCHAR(1000),
	ID_CATEGORIA INTEGER
	VALOR_TAXA_ENTREGA DECIMAl(12,2),
	ENDERECO VARCHAR(100),
	COMPLEMENTO VARCHAR(50),
	BAIRRO VARCHAR(50),
	CIDADE VARCHAR(50),
	UF VARCHAR(2),
	CEP VARCHAR(10),

	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);