CREATE TABLE PEDIDO (
	ID_PEDIDO 			INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ID_USUARIO 			INTEGER,
	ID_EMPRESA 			INTEGER,
	VALOR_SUBTOTAL 		DECIMAL(12, 2),
	VALOR_TAXA_ENTREGA 	DECIMAL(12, 2),
	VALOR_TOTAL 		DECIMAL(12, 2),
	DATA_PEDIDO 		DATETIME,
	STATUS 				CHAR(1), -- P ( em produção ), F ( finalizado ) comentário em linha do sql

	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
)