CREATE TABLE PRODUTO (
	ID_PRODUTO 			INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
		ID_EMPRESA 		INTEGER,
		ID_CATEGORIA 	INTEGER,
		NOME 			VARCHAR(100),
		DESCRICAO 		VARCHAR(500),
		ICONE 			VARCHAR(1000),
		VALOR_PRODUTO 	DECIMAL(12,2),
	INDICADOR_ATIVO 	CHAR(1),

	FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA),
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);
/* Exemplo de identação */